## src/Matrix/BUILD

cc_library(
    name = "func",
    srcs = ["Tree.cpp",
    "FruitTree.cpp",
    "ForestTree.cpp",
    "ContainerTree.cpp",
    ],
    hdrs = [
    "Tree.hpp",
    "FruitTree.hpp",
    "ForestTree.hpp",
    "ContainerTree.hpp",
    ],
    visibility = ["//visibility:public"]
)
