## src/Matrix/BUILD

cc_library(
    name = "func",
    srcs = ["Book.cpp",
    "Library.cpp",
    ],
    hdrs = ["Book.hpp",
    "Library.hpp",
    ],
    
    visibility = ["//visibility:public"]
)
