## src/main/BUILD

cc_binary(
    name = "cpp_app",
    srcs = ["main.cpp"],
    deps = [
        "//src/Fraction:Fraction",
        "//src/Matrix:Matrix",
        "//src/Toy:Toy",
        "//src/List:List",
    ]
)
