## src/Matrix/BUILD

cc_library(
    name = "func",
    srcs = ["Student2.cpp",
    "Student1Session.cpp",
    "Student2Session.cpp"
    ],
    hdrs = ["Student2.h",
    "Student1Session.h",
    "Student2Session.h"
    ],
    visibility = ["//visibility:public"]
)
