## src/Matrix/BUILD

cc_library(
    name = "func",
    srcs = ["Person.cpp",
    "Professor.cpp",
    "Student.cpp"
    ],
    hdrs = ["Person.h",
    "Professor.h",
    "Student.h"],
    visibility = ["//visibility:public"]
)
